### ISSUE TITLE
Multiple graphs?

### ISSUE THREAD

**Issue by asummers** [uesteibar/neuron#18]
How would one consume multiple graphs using Neuron? From the docs, the usage of a single config seems to disallow that. Perhaps an additional arity could be added to the query function to take in a config, so that users can populate and pass in? Or some sort of named graph in the config? Please let me know if I'm missing something obvious! This seems like a very nice product at first glance.

**Comment by uesteibar** [comment]
Hi @asummers!!

Right now, in order to use multiple graph endpoint you'd have to use each of them in different processes, where you can set your config using [`Neuron.Config.set/2`](https://hexdocs.pm/neuron/Neuron.Config.html#set/2).

Passing an extra argument to `query/1` and `mutation/1` to overwrite the config does sound like a good idea, would you like to go for it? :)

Thanks for the feedback!

**Comment by asummers** [comment]
How do you envision the config changing, since it doesn't seem to return a data structure currently for passing into the argument? Is it just a keyword list under the hood?

**Comment by uesteibar** [comment]
What do you mean by _envision the config changing_? I think I don't quite understand that question.

The config storage is implemented in the [`Neuron.Store`](https://github.com/uesteibar/neuron/blob/master/lib/neuron/store.ex) module, it's using `Application.put_env` under the hood, so in practice it's a keyword list.

**Comment by asummers** [comment]
Imagine I need to configure two graphs within the same process. They'd need to have some designation like `:facebook` and `:github`. Assume I leave config completely alone (not entirely unreasonable), then the query function would look something like `Neuron.query(some_query, url: ..., headers: ...)`. If you wanted to somehow preconfigure that, you might be able to do something like: 

```elixir
Neuron.Config.set(:github, :url, "https://...")
Neuron.Config.set(:facebook, :url, "https://...")
...
Neuron.query(query, :github)
```

If nothing is touched in the config API, you can't really use that construct at all for getting the config and would have to pass the options in by hand. That might be OK, but just confirming that's how you'd like to see it.

**Comment by uesteibar** [comment]
preconfiguring it doesn't sound bad to me, it would be a nice way to force not having the url duplicated everywhere :)

Would this work for your use case? would you like to go for it?

**Comment by asummers** [comment]
I can take a look in the next week or two. None of this sounds too difficult on the surface. Does that API sound reasonable to you? Would seem to work well for my use case, and would allow someone to hit the same endpoint with e.g. different credentials. I'll post with any further questions if I have any!

**Comment by uesteibar** [comment]
yeah, that sounds great @asummers!! If we namespace the current behaviour to `:default`, that should allow us to not do a breaking change.

Thanks for the input! Feel free to get back to me if you have any question :)

**Comment by uesteibar** [comment]
Hi @asummers! I worked on this a little bit (sorry for taking over 😅), at the end it felt like namespacing config too much would be a little messy, so I changed it so you can override options as needed in a per request basis.

Let me know what you think! https://github.com/uesteibar/neuron/pull/21

**Comment by uesteibar** [comment]
@asummers this has been release as [v0.9.0](https://github.com/uesteibar/neuron/releases/tag/v0.9.0)
