### ISSUE TITLE
Support for subscriptions

### ISSUE THREAD

**Issue by churcho** [uesteibar/neuron#28]
Does neuron support GraphQL subscriptions running off an Absinthe based server?

I will have extensive use of these in my app.

**Comment by uesteibar** [comment]
Hi @churcho!

I'm actually investigating on how to implement this properly, but as of now it's only some experiments and there's no ETA.

**Comment by alde103** [comment]
Does neuron support GraphQL subscriptions now?

**Comment by uesteibar** [comment]
Hi @alde103, no it does not support subscriptions yet. I'll open an issue shortly with a proposal though, as it seems to be a recurrently requested feature :)
