### ISSUE TITLE
How does it compare with Absinthe? Are there any differences ?

### ISSUE THREAD

**Issue by collegeimprovements** [uesteibar/neuron#3]

**Comment by uesteibar** [comment]
Hi @collegeimprovements!

If you have a look at the [docs](https://hexdocs.pm/neuron/Neuron.html) and the [usage section](https://github.com/uesteibar/neuron#usage) of the readme, you will see that while `Absinthe` is a library to **define GraphQL schemas** and basically gives you the stuff you need to create a **graphql API**, `Neuron` is a GraphQL **client**, that allows you to **consume graphql endpoints**.

`Neuron` is for Elixir basically what [Lokka](https://github.com/kadirahq/lokka) would be for JS.

Is it more clear like that? Maybe I could improve the readme to explain this better?

Thanks! :)

**Comment by uesteibar** [comment]
@collegeimprovements I'll close this issue after the clarification, thank you!
