### ISSUE TITLE
Incorrect typespec on Neuron.query/3

### ISSUE THREAD

**Issue by msimonborg** [uesteibar/neuron#31]
The typespec on `Neuron.query/3` states a return value of `Neuron.Response.t()`, but dialyzer blows up on this. The correct return type should be something like `{:ok, Neuron.Response.t()} | {:error, response :: term}`

**Comment by uesteibar** [comment]
Good catch, thanks for reporting!

Could you check if #32 fixes it for you?

**Comment by msimonborg** [comment]
It works! I suppose if you wanted more specific error typing it would be `{:error, Neuron.Response.t() | Neuron.JSONParseError.t()}`, but the current solution works well enough for me.

Thanks!

**Comment by uesteibar** [comment]
Nice! 🎉 actually yeah, there's no need to be more generic, so I'll switch it to that and release it

**Comment by uesteibar** [comment]
This has been released on [v1.1.1](https://github.com/uesteibar/neuron/blob/master/CHANGELOG.md#111-2019-03-14).

Thanks for reporting it! ❤️

**Comment by msimonborg** [comment]
Thank you!
