### ISSUE TITLE
Config not working in Elixir Release

### ISSUE THREAD

**Issue by coladarci** [uesteibar/neuron#39]
Hi, I am having an extremely hard time pinning this problem down, so forgive me if I struggle to make this actionable. But here it goes - 

I have a brand new phoenix install running on Elixir 1.9. I am using latest Neuron and have it working locally. I configure it like this:
```
    Neuron.Config.set(url: "http://my-api-server/gql")
    Neuron.Config.set(headers: [authorization: "Bearer my-token])
```

It works well locally. 

I then make a release using the new `mix release`, and when I run the release, my api calls seem to be ignoring the `Neuron.Config.set(url: "http://my-api-server/gql")` and hitting `/` (which is my phoenix app, not api server). 

I don't have any env vars; this is all hard-coded (for now), so it can't be a config issue that I can spot. I do know elixir 1.9 changed how run time config works, so perhaps this is a real breaking change for your library?

I'm happy to in anyway to pin this down, I'm just sort of out of ideas!

Thanks..

**Comment by uesteibar** [comment]
Hi @coladarci! Thanks for reporting this :)

I was not aware of this change on elixir 1.9, but I had a quick look and I don't see exactly how it would affect the use case, but I'm probably missing something. Where exactly are you executing that code example? That would help understanding the situation.

Could you provide a repository with a minimal example that reproduces this issue? We can use any public graphql api like https://swapi.graph.cool. I'm happy to take a look at that and try to figure out what's going on 😃

**Comment by coladarci** [comment]
Thanks, @uesteibar for the quick response, I put together a project for this and... it doesn't happen there. 

![bitmoji](https://render.bitstrips.com/v2/cpanel/4a148723-fbbf-4972-8e6e-120148c5a497-e886e5bd-f4e1-4700-a7de-3e940ed0226e-v1.png?transparent=1&palette=1&width=246)

I will dig in and eventually find out something super strange, I imagine. I'll close this when I get to the bottom of it and confirm it's just me being a dumb dumb.

Appreciate your response..

**Comment by uesteibar** [comment]
Mmm interesting that it doesn't happen in a brand new project, could you tell me in which file you're running this code? that could help on figuring out what's happening there :)

**Comment by coladarci** [comment]
In the same project I tried setting the config both in a context function and in the controller; both worked. In my project I have it happening inside a context function. 

Just for an update, this has gotten even more strange. From my testing, it *does* work when I do a `mix release`, it's that when I run this inside Docker, it starts to fail. 

Needless to say, I am losing my mind :) Since I can't make this happen in a test project, I'm going to close for now and I'll re-open if I discover anything interesting.. 

Appreciate it..

**Comment by uesteibar** [comment]
Wow, that it fails when running inside a docker container does sound very weird... if you somehow manage to build a project in which we can reproduce it I'll be glad to have a look :)

Thanks for the time put into reporting this! 😃

**Comment by coladarci** [comment]
I got to the bottom of it - it was cryptic and specific to us. the tl;dr is that the URL being used was invalid and it failed in absolutely strange ways. Sorry for the fire drill :)

**Comment by uesteibar** [comment]
@coladarci happy to hear you found the issue! Do you think there's something we could do in this library to make the error more obvious?

**Comment by coladarci** [comment]
Nope :)
