### ISSUE TITLE
"(Neuron.MissingFragmentsError) Fragments on not found"

### ISSUE THREAD

**Issue by fschuindt** [uesteibar/neuron#55]
Here's my query string:

```
{
  nodes(ids: ["gid://shopify/Product/95039285", "gid://shopify/Product/859892931"]) {
    ...on Product {
      title
      description
      metafields (first: 10) {
        edges {
          node {
            key
            value
          }
       }
      }
    }
  }
}
```

And my code:
```elixir
Neuron.Config.set(url: ENV.graphql_url())
Neuron.Config.set(headers: [
  "Content-Type": "application/graphql",
    "X-Shopify-Access-Token": ENV.pwd()
])

Neuron.query(query)
```

It errors with:
```
** (Neuron.MissingFragmentsError) Fragments on not found
    (neuron) lib/neuron/fragment.ex:58: Neuron.Fragment.insert_into_query/1
    (neuron) lib/neuron.ex:97: Neuron.query/3
```

Am I doing anything wrong?  
Thank you!

**Comment by uesteibar** [comment]
Hi @fschuindt!

Just to make sure, I see you're using a `Product` fragment, is it registered? You can do so using [`Neuron.Fragment.register/1`](https://hexdocs.pm/neuron/Neuron.Fragment.html#content). After that you should be able to use it in your queries.

**Comment by fschuindt** [comment]
Thank you!

**Comment by choiway** [comment]
@fschuindt I'm having the same problem. How did you  get this work? I'm running into an ellipses error

**Comment by uesteibar** [comment]
@choiway what query are you running and what's the error you're getting?

**Comment by choiway** [comment]
@uesteibar thanks for the following up. I figured it out....had an issue with spaces.
