### ISSUE TITLE
Bug in returning a JSONParseError

### ISSUE THREAD

**Issue by krisalyssa** [uesteibar/neuron#59]
`Neuron.Connection.Http` can return a `JSONParseError` (https://github.com/uesteibar/neuron/blob/master/lib/neuron/connection/http.ex#L73):

```elixir
  defp handle_unparsable(response, error) do
    {
      :error,
      %JSONParseError{
        response: build_response(response),
        error: error
      }
    }
  end
```

According to the typespec for `JSONParseError`, `response` is supposed to be a `Neuron.Response.t()`, but `build_response/1` returns a tuple (https://github.com/uesteibar/neuron/blob/master/lib/neuron/connection/http.ex#L62):

```elixir
  defp build_response(response) do
    {
      :error,
      %Response{
        status_code: response.status_code,
        body: response.body,
        headers: response.headers
      }
    }
  end
```

**Comment by uesteibar** [comment]
Good catch @CraigCottingham! The fix should be fairly easy, do you want to tackle it yourself? Otherwise I'll do it but it will take a bit :)

Thanks for reporting!

**Comment by krisalyssa** [comment]
I've already forked and am working on a fix.

Is it fair to assume that the typespec is what should be considered correct, not what the code is currently returning?

**Comment by uesteibar** [comment]
indeed! that sounds right
