### ISSUE TITLE
InputTypes

### ISSUE THREAD

**Issue by JamesArthurHolland** [uesteibar/neuron#62]
Hi, does neuron support input types?

If so, could you please explain it in documentation?

Thanks,

Jamie

**Comment by uesteibar** [comment]
Hi! What do you mean by _input type_? As far as I know there's nothing stopping you from doing something like

```elixir
Neuron.query("""
      mutation createUser($input: UserCreationInput!) {
        createUser(input: $input) {
          id
          name
        }
      }
  """,
  %{
    input: %{
      name: "my-name",
      age: 25
    }
  }
)
```

If something like that doesn't work then it's a bug and we should fix it.

Is that what you're looking for?

**Comment by JamesArthurHolland** [comment]
Yea that's great. It works. Thanks
