### ISSUE TITLE
Trying to send Queries using GZIP?

### ISSUE THREAD

**Issue by onizam95** [uesteibar/neuron#66]
Can anyone please explain how can I send data in compressed form using Gzip? 
Not able to do it with Neuron.

**Comment by uesteibar** [comment]
I haven't tried it myself, but I believe you should be able to do this by [using a custom `Connection`](https://github.com/uesteibar/neuron#connection)

**Comment by uesteibar** [comment]
@onizam95 did this answer your Q? if it did or if I don't get a response, I'll close the issue
